In [193]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [194]:
a=pd.read_csv("train.csv")
pd.options.display.max_columns=81

In [195]:
a

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0            Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1            Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2            Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3            Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4            Lvl    AllPub       FR2       Gtl      NoRidge       Norm   
...          ...       ...       ...       ...          ...        ...   
1455         Lvl    AllPub    Inside       Gtl      Gilbert       Norm   
1456         Lvl    AllPub    Inside       Gtl       NWAmes       Norm   
1457         Lvl    AllPub    Inside       Gtl      Crawfor       Norm   
1458         Lvl    AllPub    Inside       Gtl        NAmes       Norm   
1459         Lvl    AllPub    Inside       Gtl      Edwards       Norm   

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0          Norm     1Fam     2Story            7            5       2003   
1          Norm     1Fam     1Story            6            8       1976   
2          Norm     1Fam     2Story            7            5       2001   
3          Norm     1Fam     2Story            7            5       1915   
4          Norm     1Fam     2Story            8            5       2000   
...         ...      ...        ...          ...          ...        ...   
1455       Norm     1Fam     2Story            6            5       1999   
1456       Norm     1Fam     1Story            6            6       1978   
1457       Norm     1Fam     2Story            7            9       1941   
1458       Norm     1Fam     1Story            5            6       1950   
1459       Norm     1Fam     1Story            5            6       1965   

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0             2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1             1976     Gable  CompShg     MetalSd     MetalSd       None   
2             2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3             1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4             2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   
...            ...       ...      ...         ...         ...        ...   
1455          2000     Gable  CompShg     VinylSd     VinylSd       None   
1456          1988     Gable  CompShg     Plywood     Plywood      Stone   
1457          2006     Gable  CompShg     CemntBd     CmentBd       None   
1458          1996       Hip  CompShg     MetalSd     MetalSd       None   
1459          1965     Gable  CompShg     HdBoard     HdBoard       None   

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
0          196.0        Gd        TA      PConc       Gd       TA   
1            0.0        TA        TA     CBlock       Gd       TA   
2          162.0        Gd        TA      PConc       Gd       TA   
3            0.0        TA        TA     BrkTil       TA       Gd   

In [196]:
(a.corr()>0.4).sum()

Id                1
MSSubClass        1
LotFrontage       4
LotArea           2
OverallQual      13
OverallCond       1
YearBuilt         8
YearRemodAdd      7
MasVnrArea        3
BsmtFinSF1        4
BsmtFinSF2        1
BsmtUnfSF         2
TotalBsmtSF       9
1stFlrSF         11
2ndFlrSF          6
LowQualFinSF      1
GrLivArea        14
BsmtFullBath      2
BsmtHalfBath      1
FullBath         11
HalfBath          3
BedroomAbvGr      4
KitchenAbvGr      1
TotRmsAbvGrd      8
Fireplaces        4
GarageYrBlt       8
GarageCars       11
GarageArea       10
WoodDeckSF        1
OpenPorchSF       1
EnclosedPorch     1
3SsnPorch         1
ScreenPorch       1
PoolArea          1
MiscVal           1
MoSold            1
YrSold            1
SalePrice        14
dtype: int64

# Univerient Regression

In [197]:
x=a[["GrLivArea"]]
x

GrLivArea
0          1710
1          1262
2          1786
3          1717
4          2198
...         ...
1455       1647
1456       2073
1457       2340
1458       1078
1459       1256

[1460 rows x 1 columns]

In [198]:
y=a[["SalePrice"]]
y

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [199]:
x.isnull().sum()

GrLivArea    0
dtype: int64

In [200]:
y.isnull().sum()

SalePrice    0
dtype: int64

In [201]:
x.shape

(1460, 1)

In [202]:
y.shape

(1460, 1)

In [203]:
from sklearn.model_selection import train_test_split

In [204]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.1,shuffle=True,random_state=2)

In [205]:
from sklearn.linear_model import LinearRegression

In [206]:
model=LinearRegression(fit_intercept=True,normalize=False,copy_X=True,n_jobs=None,positive=False)

In [207]:
model.fit(xtrain,ytrain)

LinearRegression()

In [208]:
model.predict(xtest)

array([[209191.77342239],
       [202048.48941908],
       [353403.28960526],
       [151838.44968563],
       [163329.81960401],
       [213125.75591697],
       [185587.87845492],
       [200909.70501275],
       [140761.18318773],
       [213022.23006185],
       [188590.12825341],
       [163329.81960401],
       [124921.7273543 ],
       [138897.71779557],
       [148422.09646665],
       [259505.33901096],
       [257020.71848807],
       [191385.32634166],
       [266855.67472452],
       [320067.96425646],
       [230518.09957722],
       [175028.24123262],
       [181860.94767058],
       [254225.52039981],
       [327625.35168026],
       [200806.17915763],
       [166849.6986781 ],
       [263853.42492602],
       [178134.01688624],
       [305160.24111911],
       [190453.59364558],
       [169334.319201  ],
       [283626.86325404],
       [130408.59767568],
       [191695.90390703],
       [205775.42020342],
       [123368.83952749],
       [270375.55379861],
       [2529

In [209]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [210]:
mean_absolute_error(ytest,model.predict(xtest))

38885.80411782718

In [211]:
mean_squared_error(ytest,model.predict(xtest))

3115481567.0905743

In [212]:
r2_score(ytest,model.predict(xtest))

0.6067608955794143

In [213]:
model.score(xtest,ytest)

0.6067608955794143

In [214]:
Univerient=[model.score(xtest,ytest)]

In [215]:
b=pd.DataFrame(Univerient,columns=["Univerient_Score"],index=["Univerent"])
b

Univerient_Score
Univerent          0.606761

In [216]:
b[["Mean_Absolute_Error"]]=[mean_absolute_error(ytest,model.predict(xtest))]

In [217]:
b[["Mean_Squared_Error"]]=[mean_squared_error(ytest,model.predict(xtest))]

In [218]:
b[["R2_Score"]]=[r2_score(ytest,model.predict(xtest))]

In [219]:
b

Univerient_Score  Mean_Absolute_Error  Mean_Squared_Error  R2_Score
Univerent          0.606761         38885.804118        3.115482e+09  0.606761

In [220]:
b.loc["==================="]=["=======","============","============","======="]

In [221]:
b

Univerient_Score Mean_Absolute_Error Mean_Squared_Error  \
Univerent                   0.606761        38885.804118  3115481567.090574   
===================          =======        ============       ============   

                     R2_Score  
Univerent            0.606761  
===================   =======

In [222]:
b

Univerient_Score Mean_Absolute_Error Mean_Squared_Error  \
Univerent                   0.606761        38885.804118  3115481567.090574   
===================          =======        ============       ============   

                     R2_Score  
Univerent            0.606761  
===================   =======

In [223]:
b

Univerient_Score Mean_Absolute_Error Mean_Squared_Error  \
Univerent                   0.606761        38885.804118  3115481567.090574   
===================          =======        ============       ============   

                     R2_Score  
Univerent            0.606761  
===================   =======

# Multi Regression

In [224]:
(a.corr()>0.4).sum()

Id                1
MSSubClass        1
LotFrontage       4
LotArea           2
OverallQual      13
OverallCond       1
YearBuilt         8
YearRemodAdd      7
MasVnrArea        3
BsmtFinSF1        4
BsmtFinSF2        1
BsmtUnfSF         2
TotalBsmtSF       9
1stFlrSF         11
2ndFlrSF          6
LowQualFinSF      1
GrLivArea        14
BsmtFullBath      2
BsmtHalfBath      1
FullBath         11
HalfBath          3
BedroomAbvGr      4
KitchenAbvGr      1
TotRmsAbvGrd      8
Fireplaces        4
GarageYrBlt       8
GarageCars       11
GarageArea       10
WoodDeckSF        1
OpenPorchSF       1
EnclosedPorch     1
3SsnPorch         1
ScreenPorch       1
PoolArea          1
MiscVal           1
MoSold            1
YrSold            1
SalePrice        14
dtype: int64

In [225]:
x1=a[["OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea"]]
x1

OverallQual  1stFlrSF  GrLivArea  FullBath  GarageCars  GarageArea
0               7       856       1710         2           2         548
1               6      1262       1262         2           2         460
2               7       920       1786         2           2         608
3               7       961       1717         1           3         642
4               8      1145       2198         2           3         836
...           ...       ...        ...       ...         ...         ...
1455            6       953       1647         2           2         460
1456            6      2073       2073         2           2         500
1457            7      1188       2340         2           1         252
1458            5      1078       1078         1           1         240
1459            5      1256       1256         1           1         276

[1460 rows x 6 columns]

In [226]:
x1.isnull().sum()

OverallQual    0
1stFlrSF       0
GrLivArea      0
FullBath       0
GarageCars     0
GarageArea     0
dtype: int64

In [227]:
y1=a[["SalePrice"]]
y1

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [228]:
y1.isnull().sum()

SalePrice    0
dtype: int64

In [229]:
x1.shape

(1460, 6)

In [230]:
y1.shape

(1460, 1)

In [231]:
from sklearn.model_selection import train_test_split

In [232]:
x1train,x1test,y1train,y1test=train_test_split(x1,y1,test_size=0.1,shuffle=True,random_state=None)

In [233]:
from sklearn.linear_model import LinearRegression

In [234]:
model=LinearRegression()

In [235]:
model.fit(x1train,y1train)

LinearRegression()

In [236]:
model.predict(x1test)

array([[165512.4238161 ],
       [188022.4353145 ],
       [276519.713361  ],
       [143463.18374363],
       [167309.33941611],
       [126427.87196671],
       [170909.16801127],
       [210765.07390966],
       [ 57470.3096896 ],
       [143973.78251332],
       [ 88733.2644564 ],
       [165242.63109491],
       [172368.6844649 ],
       [274512.3714218 ],
       [188084.99736203],
       [233402.61966745],
       [164434.68836554],
       [ 80202.08845551],
       [350129.67766991],
       [143973.78251332],
       [400079.26086594],
       [171195.5159507 ],
       [208298.5052391 ],
       [217329.68255008],
       [177459.85274914],
       [219119.44400257],
       [120735.49993434],
       [133985.08806931],
       [ 92576.05469822],
       [169461.32130656],
       [112687.10468913],
       [151272.90199357],
       [221971.59797614],
       [256616.06676256],
       [ 88160.66807242],
       [142925.93345243],
       [224297.66533727],
       [210602.09611029],
       [1767

In [237]:
mean_absolute_error(y1test,model.predict(x1test))

24994.30649901497

In [238]:
mean_squared_error(y1test,model.predict(x1test))

1220577200.4239545

In [239]:
r2_score(y1test,model.predict(x1test))

0.7886602928373735

In [240]:
from sklearn.metrics import f1_score

In [241]:
model.score(x1test,y1test)

0.7886602928373735

In [242]:
b.loc["MultiVenient"]=["Multiverient_Score","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [243]:
b.loc["MultiVenient_score"]=[model.score(x1test,y1test),mean_absolute_error(y1test,model.predict(x1test)),mean_squared_error(y1test,model.predict(x1test)),model.score(x1test,y1test)]

In [244]:
b.loc["======================="]=["=============","=============","=============","=========="]

In [245]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                          0.606761         38885.804118   
===================                 =======         ============   
MultiVenient             Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                  0.78866         24994.306499   
=======================       =============        =============   

                         Mean_Squared_Error    R2_Score  
Univerent                 3115481567.090574    0.606761  
===================            ============     =======  
MultiVenient             Mean_Squared_Error    R2_Score  
MultiVenient_score        1220577200.423954     0.78866  
=======================       =============  ==========

# Polynomial Regression

In [246]:
x2=a[["OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea"]]
x2

OverallQual  1stFlrSF  GrLivArea  FullBath  GarageCars  GarageArea
0               7       856       1710         2           2         548
1               6      1262       1262         2           2         460
2               7       920       1786         2           2         608
3               7       961       1717         1           3         642
4               8      1145       2198         2           3         836
...           ...       ...        ...       ...         ...         ...
1455            6       953       1647         2           2         460
1456            6      2073       2073         2           2         500
1457            7      1188       2340         2           1         252
1458            5      1078       1078         1           1         240
1459            5      1256       1256         1           1         276

[1460 rows x 6 columns]

In [247]:
y2=a[["SalePrice"]]
y2

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [248]:
y2.isnull().sum()

SalePrice    0
dtype: int64

In [249]:
x2.isnull().sum()

OverallQual    0
1stFlrSF       0
GrLivArea      0
FullBath       0
GarageCars     0
GarageArea     0
dtype: int64

In [250]:
x2.shape

(1460, 6)

In [251]:
y2.shape

(1460, 1)

In [252]:
from sklearn.model_selection import train_test_split

In [253]:
x2train,x2test,y2train,y2test=train_test_split(x2,y2,test_size=0.1,shuffle=True,random_state=2)

In [254]:
from sklearn.preprocessing import PolynomialFeatures

In [255]:
poly=PolynomialFeatures(degree=2)

In [256]:
poly1=PolynomialFeatures(include_bias=True)

In [257]:
poly2=PolynomialFeatures(order='C')

In [258]:
poly2=PolynomialFeatures(interaction_only=False)

In [259]:
poly.fit_transform(x2train,x2test)

array([[1.00000e+00, 6.00000e+00, 8.64000e+02, ..., 4.00000e+00,
        7.96000e+02, 1.58404e+05],
       [1.00000e+00, 5.00000e+00, 6.72000e+02, ..., 1.00000e+00,
        2.40000e+02, 5.76000e+04],
       [1.00000e+00, 7.00000e+00, 1.08600e+03, ..., 4.00000e+00,
        8.18000e+02, 1.67281e+05],
       ...,
       [1.00000e+00, 5.00000e+00, 1.26900e+03, ..., 1.00000e+00,
        3.08000e+02, 9.48640e+04],
       [1.00000e+00, 9.00000e+00, 1.47600e+03, ..., 9.00000e+00,
        2.57400e+03, 7.36164e+05],
       [1.00000e+00, 5.00000e+00, 8.42000e+02, ..., 1.00000e+00,
        2.50000e+02, 6.25000e+04]])

In [260]:
poly.fit(x2train,x2test)

PolynomialFeatures()

In [261]:
from sklearn.linear_model import LinearRegression

In [262]:
model=LinearRegression()

In [263]:
model.fit(x2train,y2train)

LinearRegression()

In [264]:
model.predict(x2test)

array([[237796.45929968],
       [184185.77034097],
       [317468.16024812],
       [225606.26744901],
       [207502.0397977 ],
       [220626.09854719],
       [223630.52239578],
       [182391.59514827],
       [101967.51885746],
       [311365.04314372],
       [199787.27585475],
       [207502.0397977 ],
       [121160.51330754],
       [140125.51912347],
       [102592.40617894],
       [245132.16553593],
       [267692.99153541],
       [274335.41500958],
       [216473.26780988],
       [314998.07976757],
       [319322.54966396],
       [166281.94638547],
       [192406.775826  ],
       [233050.02160995],
       [364192.53796494],
       [233279.10331531],
       [185199.96455842],
       [250092.00111015],
       [219490.99976547],
       [343746.95654264],
       [299950.3245517 ],
       [189313.25340234],
       [265831.03146879],
       [ 96472.43076968],
       [204884.71549587],
       [235488.02006044],
       [135073.00261057],
       [295965.90194258],
       [3136

In [265]:
mean_absolute_error(y2test,model.predict(x2test))

26132.90996878154

In [266]:
mean_squared_error(y2test,model.predict(x2test))

1437292992.4483628

In [267]:
r2_score(y2test,model.predict(x2test))

0.8185834847778619

In [268]:
model.score(x2test,y2test)

0.8185834847778619

In [269]:
b.loc["Polynomial"]=["Polynomial_Score","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [270]:
b.loc["Polynomial_score"]=[model.score(x2test,y2test),mean_absolute_error(y2test,model.predict(x2test)),mean_squared_error(y2test,model.predict(x2test)),r2_score(y2test,model.predict(x2test))]

In [271]:
b.loc["======================"]=["=============","=============","=============","=========="]

In [272]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                          0.606761         38885.804118   
===================                 =======         ============   
MultiVenient             Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                  0.78866         24994.306499   
=======================       =============        =============   
Polynomial                 Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                   0.818583         26132.909969   
======================        =============        =============   

                         Mean_Squared_Error    R2_Score  
Univerent                 3115481567.090574    0.606761  
===================            ============     =======  
MultiVenient             Mean_Squared_Error    R2_Score  
MultiVenient_score        1220577200.423954     0.78866  
=======================       =============  ==========  
Polynomial               Mean_Squared_Error    R2_Score  
Polynomial_score          1437292992.448363    0.818583  
======================        =============  ==========

# StandardScaler with Univerient

In [273]:
from sklearn.preprocessing import StandardScaler

In [274]:
ss=StandardScaler(copy=True, with_mean=True, with_std=True)

In [275]:
ss.fit_transform(g)

array([[ 0.37033344],
       [-0.48251191],
       [ 0.51501256],
       ...,
       [ 1.56964722],
       [-0.83278768],
       [-0.49393395]])

In [276]:
g=a[["GrLivArea"]]
g

GrLivArea
0          1710
1          1262
2          1786
3          1717
4          2198
...         ...
1455       1647
1456       2073
1457       2340
1458       1078
1459       1256

[1460 rows x 1 columns]

In [277]:
x3=ss.fit_transform(g)
x3

array([[ 0.37033344],
       [-0.48251191],
       [ 0.51501256],
       ...,
       [ 1.56964722],
       [-0.83278768],
       [-0.49393395]])

In [278]:
x3=pd.DataFrame(x3)
x3

0
0     0.370333
1    -0.482512
2     0.515013
3     0.383659
4     1.299326
...        ...
1455  0.250402
1456  1.061367
1457  1.569647
1458 -0.832788
1459 -0.493934

[1460 rows x 1 columns]

In [279]:
y3=a[["SalePrice"]]
y3

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [280]:
from sklearn.model_selection import train_test_split

In [281]:
x3train,x3test,y3train,y3test=train_test_split(x3,y3,test_size=0.1,shuffle=True,random_state=150)

In [282]:
from sklearn.linear_model import LinearRegression

In [283]:
model=LinearRegression()

In [284]:
model.fit(x3train,y3train)

LinearRegression()

In [285]:
model.predict(x3test)

array([[160776.67737343],
       [226594.07574108],
       [261064.89672161],
       [225969.2270224 ],
       [247214.08345753],
       [180980.11927743],
       [194518.50818217],
       [266688.53518973],
       [179105.57312139],
       [130159.0901581 ],
       [212639.12102389],
       [152341.21967125],
       [236695.79669308],
       [138906.97221963],
       [160360.11156098],
       [237945.49413044],
       [316988.85704349],
       [138386.26495406],
       [117557.97433139],
       [283247.02623476],
       [129534.24143942],
       [255337.11680037],
       [128180.40254895],
       [235133.67489638],
       [142447.78162548],
       [195768.20561953],
       [149321.11753096],
       [189415.57697961],
       [185874.76757376],
       [225344.37830372],
       [167650.01327892],
       [211076.99922719],
       [179105.57312139],
       [153486.7756555 ],
       [150987.38078078],
       [162442.94062325],
       [124639.5931431 ],
       [159943.54574853],
       [1896

In [286]:
mean_absolute_error(y3test,model.predict(x3test))

40232.13229894883

In [287]:
mean_squared_error(y3test,model.predict(x3test))

3851185498.488252

In [288]:
r2_score(y3test,model.predict(x3test))

0.5150280669014105

In [289]:
model.score(x3test,y3test)

0.5150280669014105

In [290]:
b.loc["Unuverient with StandardScaler"]=["StandardScale_Score","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [291]:
b.loc["StandardScaler_score"]=[model.score(x3test,y3test),mean_absolute_error(y3test,model.predict(x3test)),mean_squared_error(y3test,model.predict(x3test)),r2_score(y3test,model.predict(x3test))]

In [292]:
b.loc["============================="]=["=============","=============","=============","=========="]

In [293]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                                  0.606761         38885.804118   
===================                         =======         ============   
MultiVenient                     Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                          0.78866         24994.306499   
=======================               =============        =============   
Polynomial                         Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                           0.818583         26132.909969   
======================                =============        =============   
Unuverient with StandardScaler  StandardScale_Score  Mean_Absolute_Error   
StandardScaler_score                       0.515028         40232.132299   
=============================         =============        =============   

                                Mean_Squared_Error    R2_Score  
Univerent                        3115481567.090574    0.606761  
===================                   ============     =======  
MultiVenient                    Mean_Squared_Error    R2_Score  
MultiVenient_score               1220577200.423954     0.78866  
=======================              =============  ==========  
Polynomial                      Mean_Squared_Error    R2_Score  
Polynomial_score                 1437292992.448363    0.818583  
======================               =============  ==========  
Unuverient with StandardScaler  Mean_Squared_Error    R2_Score  
StandardScaler_score             3851185498.488252    0.515028  
=============================        =============  ==========

# MinMaxScaler with Univerient

In [294]:
from sklearn.preprocessing import MinMaxScaler

In [295]:
mm=MinMaxScaler(feature_range=(0, 1), copy=True, clip=False)

In [296]:
g1=a[["GrLivArea"]]
g1

GrLivArea
0          1710
1          1262
2          1786
3          1717
4          2198
...         ...
1455       1647
1456       2073
1457       2340
1458       1078
1459       1256

[1460 rows x 1 columns]

In [297]:
x4=mm.fit_transform(g1)
x4

array([[0.25923135],
       [0.17483044],
       [0.27354936],
       ...,
       [0.37792012],
       [0.14016579],
       [0.17370008]])

In [298]:
y4=a[["SalePrice"]]
y4

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [299]:
x4=pd.DataFrame(x4)
x4

0
0     0.259231
1     0.174830
2     0.273549
3     0.260550
4     0.351168
...        ...
1455  0.247362
1456  0.327619
1457  0.377920
1458  0.140166
1459  0.173700

[1460 rows x 1 columns]

In [300]:
y4

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [301]:
from sklearn.model_selection import train_test_split

In [302]:
x4train,x4test,y4train,y4test=train_test_split(x4,y4,test_size=0.1,shuffle=True,random_state=2)

In [303]:
from sklearn.linear_model import LinearRegression

In [304]:
model=LinearRegression()

In [305]:
model.fit(x4train,y4train)

LinearRegression()

In [306]:
model.predict(x4test)

array([[209191.77342239],
       [202048.48941908],
       [353403.28960526],
       [151838.44968563],
       [163329.81960401],
       [213125.75591697],
       [185587.87845492],
       [200909.70501275],
       [140761.18318773],
       [213022.23006185],
       [188590.12825341],
       [163329.81960401],
       [124921.7273543 ],
       [138897.71779557],
       [148422.09646665],
       [259505.33901096],
       [257020.71848807],
       [191385.32634166],
       [266855.67472452],
       [320067.96425646],
       [230518.09957722],
       [175028.24123262],
       [181860.94767058],
       [254225.52039981],
       [327625.35168026],
       [200806.17915763],
       [166849.6986781 ],
       [263853.42492602],
       [178134.01688624],
       [305160.24111911],
       [190453.59364558],
       [169334.319201  ],
       [283626.86325404],
       [130408.59767568],
       [191695.90390703],
       [205775.42020342],
       [123368.83952749],
       [270375.55379861],
       [2529

In [307]:
mean_absolute_error(y4test,model.predict(x4test))

38885.80411782718

In [308]:
mean_squared_error(y4test,model.predict(x4test))

3115481567.090574

In [309]:
r2_score(y4test,model.predict(x4test))

0.6067608955794144

In [310]:
model.score(x4test,y4test)

0.6067608955794144

In [311]:
b.loc["Univerient with MinMaxScaler"]=["MinMaxScaler","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [312]:
b.loc["MinMaxScaler_score"]=[model.score(x4test,y4test),mean_absolute_error(y4test,model.predict(x4test)),mean_squared_error(y4test,model.predict(x4test)),r2_score(y4test,model.predict(x4test))]

In [313]:
b.loc["============================"]=["=============","=============","=============","=========="]

In [314]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                                  0.606761         38885.804118   
===================                         =======         ============   
MultiVenient                     Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                          0.78866         24994.306499   
=======================               =============        =============   
Polynomial                         Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                           0.818583         26132.909969   
======================                =============        =============   
Unuverient with StandardScaler  StandardScale_Score  Mean_Absolute_Error   
StandardScaler_score                       0.515028         40232.132299   
=============================         =============        =============   
Univerient with MinMaxScaler           MinMaxScaler  Mean_Absolute_Error   
MinMaxScaler_score                         0.606761         38885.804118   
============================          =============        =============   

                                Mean_Squared_Error    R2_Score  
Univerent                        3115481567.090574    0.606761  
===================                   ============     =======  
MultiVenient                    Mean_Squared_Error    R2_Score  
MultiVenient_score               1220577200.423954     0.78866  
=======================              =============  ==========  
Polynomial                      Mean_Squared_Error    R2_Score  
Polynomial_score                 1437292992.448363    0.818583  
======================               =============  ==========  
Unuverient with StandardScaler  Mean_Squared_Error    R2_Score  
StandardScaler_score             3851185498.488252    0.515028  
=============================        =============  ==========  
Univerient with MinMaxScaler    Mean_Squared_Error    R2_Score  
MinMaxScaler_score               3115481567.090574    0.606761  
============================         =============  ==========

# StandardScaler with Multi Regression

In [315]:
from sklearn.preprocessing import StandardScaler

In [316]:
p=a[["OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea"]]
p

OverallQual  1stFlrSF  GrLivArea  FullBath  GarageCars  GarageArea
0               7       856       1710         2           2         548
1               6      1262       1262         2           2         460
2               7       920       1786         2           2         608
3               7       961       1717         1           3         642
4               8      1145       2198         2           3         836
...           ...       ...        ...       ...         ...         ...
1455            6       953       1647         2           2         460
1456            6      2073       2073         2           2         500
1457            7      1188       2340         2           1         252
1458            5      1078       1078         1           1         240
1459            5      1256       1256         1           1         276

[1460 rows x 6 columns]

In [317]:
sss=StandardScaler()

In [318]:
x5=sss.fit_transform(p)

In [319]:
x5=pd.DataFrame(x5)
x5

0         1         2         3         4         5
0     0.651479 -0.793434  0.370333  0.789741  0.311725  0.351000
1    -0.071836  0.257140 -0.482512  0.789741  0.311725 -0.060731
2     0.651479 -0.627826  0.515013  0.789741  0.311725  0.631726
3     0.651479 -0.521734  0.383659 -1.026041  1.650307  0.790804
4     1.374795 -0.045611  1.299326  0.789741  1.650307  1.698485
...        ...       ...       ...       ...       ...       ...
1455 -0.071836 -0.542435  0.250402  0.789741  0.311725 -0.060731
1456 -0.071836  2.355701  1.061367  0.789741  0.311725  0.126420
1457  0.651479  0.065656  1.569647  0.789741 -1.026858 -1.033914
1458 -0.795151 -0.218982 -0.832788 -1.026041 -1.026858 -1.090059
1459 -0.795151  0.241615 -0.493934 -1.026041 -1.026858 -0.921624

[1460 rows x 6 columns]

In [320]:
y5=a[["SalePrice"]]
y5

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [321]:
from sklearn.model_selection import train_test_split

In [322]:
x5train,x5test,y5train,y5test=train_test_split(x5,y5,test_size=0.1,shuffle=True,random_state=2)

In [323]:
from sklearn.linear_model import LinearRegression

In [324]:
model=LinearRegression()

In [325]:
model.fit(x5train,y5train)

LinearRegression()

In [326]:
model.predict(x5test)

array([[237796.45929967],
       [184185.77034098],
       [317468.16024811],
       [225606.26744901],
       [207502.0397977 ],
       [220626.09854719],
       [223630.52239578],
       [182391.59514827],
       [101967.51885745],
       [311365.04314372],
       [199787.27585475],
       [207502.0397977 ],
       [121160.51330754],
       [140125.51912347],
       [102592.40617896],
       [245132.16553593],
       [267692.99153542],
       [274335.41500958],
       [216473.26780988],
       [314998.07976756],
       [319322.54966398],
       [166281.94638547],
       [192406.775826  ],
       [233050.02160996],
       [364192.53796494],
       [233279.10331531],
       [185199.96455843],
       [250092.00111015],
       [219490.99976547],
       [343746.95654264],
       [299950.32455171],
       [189313.25340235],
       [265831.0314688 ],
       [ 96472.43076967],
       [204884.71549587],
       [235488.02006044],
       [135073.00261056],
       [295965.90194259],
       [3136

In [327]:
mean_absolute_error(y5test,model.predict(x5test))

26132.90996878197

In [328]:
mean_squared_error(y5test,model.predict(x5test))

1437292992.4484153

In [329]:
r2_score(y5test,model.predict(x5test))

0.8185834847778553

In [330]:
model.score(x5test,y5test)

0.8185834847778553

In [331]:
b.loc["Multivenient with StandardScaler"]=["StandardScaler","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [332]:
b.loc[" Multi_StandardScaler_score"]=[model.score(x5test,y5test),mean_absolute_error(y5test,model.predict(x5test)),mean_squared_error(y5test,model.predict(x5test)),r2_score(y5test,model.predict(x5test))]

In [333]:
b.loc["=============================-"]=["=============","=============","=============","=========="]

# MinMaxScaler

In [334]:
p1=a[["OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea"]]
p1

OverallQual  1stFlrSF  GrLivArea  FullBath  GarageCars  GarageArea
0               7       856       1710         2           2         548
1               6      1262       1262         2           2         460
2               7       920       1786         2           2         608
3               7       961       1717         1           3         642
4               8      1145       2198         2           3         836
...           ...       ...        ...       ...         ...         ...
1455            6       953       1647         2           2         460
1456            6      2073       2073         2           2         500
1457            7      1188       2340         2           1         252
1458            5      1078       1078         1           1         240
1459            5      1256       1256         1           1         276

[1460 rows x 6 columns]

In [335]:
MM=MinMaxScaler()

In [336]:
p1=MM.fit_transform(p1)
p1

array([[0.66666667, 0.11977972, 0.25923135, 0.66666667, 0.5       ,
        0.3864598 ],
       [0.55555556, 0.21294172, 0.17483044, 0.66666667, 0.5       ,
        0.32440056],
       [0.66666667, 0.13446535, 0.27354936, 0.66666667, 0.5       ,
        0.42877292],
       ...,
       [0.66666667, 0.19596145, 0.37792012, 0.66666667, 0.25      ,
        0.17771509],
       [0.44444444, 0.17072051, 0.14016579, 0.33333333, 0.25      ,
        0.16925247],
       [0.44444444, 0.21156494, 0.17370008, 0.33333333, 0.25      ,
        0.19464034]])

In [337]:
x6=pd.DataFrame(p1)
x6

0         1         2         3     4         5
0     0.666667  0.119780  0.259231  0.666667  0.50  0.386460
1     0.555556  0.212942  0.174830  0.666667  0.50  0.324401
2     0.666667  0.134465  0.273549  0.666667  0.50  0.428773
3     0.666667  0.143873  0.260550  0.333333  0.75  0.452750
4     0.777778  0.186095  0.351168  0.666667  0.75  0.589563
...        ...       ...       ...       ...   ...       ...
1455  0.555556  0.142038  0.247362  0.666667  0.50  0.324401
1456  0.555556  0.399036  0.327619  0.666667  0.50  0.352609
1457  0.666667  0.195961  0.377920  0.666667  0.25  0.177715
1458  0.444444  0.170721  0.140166  0.333333  0.25  0.169252
1459  0.444444  0.211565  0.173700  0.333333  0.25  0.194640

[1460 rows x 6 columns]

In [338]:
y6=a[["SalePrice"]]
y6


SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [339]:
from sklearn.model_selection import train_test_split

In [340]:
x6train,x6test,y6train,y6test=train_test_split(x6,y6,test_size=0.1,shuffle=True,random_state=2)

In [341]:
from sklearn.linear_model import LinearRegression

In [342]:
model=LinearRegression()

In [343]:
model.fit(x6train,y6train)

LinearRegression()

In [344]:
model.predict(x6test)

array([[237796.45929967],
       [184185.77034098],
       [317468.16024811],
       [225606.26744901],
       [207502.0397977 ],
       [220626.09854719],
       [223630.52239578],
       [182391.59514827],
       [101967.51885745],
       [311365.04314372],
       [199787.27585475],
       [207502.0397977 ],
       [121160.51330754],
       [140125.51912347],
       [102592.40617896],
       [245132.16553593],
       [267692.99153542],
       [274335.41500958],
       [216473.26780988],
       [314998.07976756],
       [319322.54966398],
       [166281.94638547],
       [192406.775826  ],
       [233050.02160996],
       [364192.53796494],
       [233279.10331531],
       [185199.96455842],
       [250092.00111015],
       [219490.99976547],
       [343746.95654264],
       [299950.32455171],
       [189313.25340235],
       [265831.0314688 ],
       [ 96472.43076967],
       [204884.71549587],
       [235488.02006044],
       [135073.00261056],
       [295965.90194259],
       [3136

In [345]:
mean_absolute_error(y6test,model.predict(x6test))

26132.909968781973

In [346]:
mean_squared_error(y6test,model.predict(x6test))

1437292992.448417

In [347]:
r2_score(y6test,model.predict(x6test))

0.818583484777855

In [348]:
model.score(x6test,y6test)

0.818583484777855

In [349]:
b.loc["Multivenient with MinMaxScaler"]=["MinMaxScaler","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [350]:
b.loc["Multi_MinMaxScaler_score"]=[model.score(x6test,y6test),mean_absolute_error(y6test,model.predict(x6test)),mean_squared_error(y6test,model.predict(x6test)),r2_score(y6test,model.predict(x6test))]

In [351]:
b.loc["============================.-"]=["=============","=============","=============","=========="]

In [352]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                                    0.606761         38885.804118   
===================                           =======         ============   
MultiVenient                       Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                            0.78866         24994.306499   
=======================                 =============        =============   
Polynomial                           Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                             0.818583         26132.909969   
======================                  =============        =============   
Unuverient with StandardScaler    StandardScale_Score  Mean_Absolute_Error   
StandardScaler_score                         0.515028         40232.132299   
=============================           =============        =============   
Univerient with MinMaxScaler             MinMaxScaler  Mean_Absolute_Error   
MinMaxScaler_score                           0.606761         38885.804118   
============================            =============        =============   
Multivenient with StandardScaler       StandardScaler  Mean_Absolute_Error   
 Multi_StandardScaler_score                  0.818583         26132.909969   
=============================-          =============        =============   
Multivenient with MinMaxScaler           MinMaxScaler  Mean_Absolute_Error   
Multi_MinMaxScaler_score                     0.818583         26132.909969   
============================.-          =============        =============   

                                  Mean_Squared_Error    R2_Score  
Univerent                          3115481567.090574    0.606761  
===================                     ============     =======  
MultiVenient                      Mean_Squared_Error    R2_Score  
MultiVenient_score                 1220577200.423954     0.78866  
=======================                =============  ==========  
Polynomial                        Mean_Squared_Error    R2_Score  
Polynomial_score                   1437292992.448363    0.818583  
======================                 =============  ==========  
Unuverient with StandardScaler    Mean_Squared_Error    R2_Score  
StandardScaler_score               3851185498.488252    0.515028  
=============================          =============  ==========  
Univerient with MinMaxScaler      Mean_Squared_Error    R2_Score  
MinMaxScaler_score                 3115481567.090574    0.606761  
============================           =============  ==========  
Multivenient with StandardScaler  Mean_Squared_Error    R2_Score  
 Multi_StandardScaler_score        1437292992.448415    0.818583  
=============================-         =============  ==========  
Multivenient with MinMaxScaler    Mean_Squared_Error    R2_Score  
Multi_MinMaxScaler_score           1437292992.448417    0.818583  
============================.-         =============  ==========

# StandardScaler with PonomialRegression

In [353]:
from sklearn.preprocessing import StandardScaler

In [354]:
ssw=StandardScaler()

In [355]:
p2=a[["OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea"]]
p2

OverallQual  1stFlrSF  GrLivArea  FullBath  GarageCars  GarageArea
0               7       856       1710         2           2         548
1               6      1262       1262         2           2         460
2               7       920       1786         2           2         608
3               7       961       1717         1           3         642
4               8      1145       2198         2           3         836
...           ...       ...        ...       ...         ...         ...
1455            6       953       1647         2           2         460
1456            6      2073       2073         2           2         500
1457            7      1188       2340         2           1         252
1458            5      1078       1078         1           1         240
1459            5      1256       1256         1           1         276

[1460 rows x 6 columns]

In [356]:
p4=ssw.fit_transform(p2)
p4

array([[ 0.65147924, -0.79343379,  0.37033344,  0.78974052,  0.31172464,
         0.35100032],
       [-0.07183611,  0.25714043, -0.48251191,  0.78974052,  0.31172464,
        -0.06073101],
       [ 0.65147924, -0.62782603,  0.51501256,  0.78974052,  0.31172464,
         0.63172623],
       ...,
       [ 0.65147924,  0.06565646,  1.56964722,  0.78974052, -1.02685765,
        -1.03391416],
       [-0.79515147, -0.21898188, -0.83278768, -1.02604084, -1.02685765,
        -1.09005935],
       [-0.79515147,  0.2416147 , -0.49393395, -1.02604084, -1.02685765,
        -0.9216238 ]])

In [357]:
x7=pd.DataFrame(p4)
x7

0         1         2         3         4         5
0     0.651479 -0.793434  0.370333  0.789741  0.311725  0.351000
1    -0.071836  0.257140 -0.482512  0.789741  0.311725 -0.060731
2     0.651479 -0.627826  0.515013  0.789741  0.311725  0.631726
3     0.651479 -0.521734  0.383659 -1.026041  1.650307  0.790804
4     1.374795 -0.045611  1.299326  0.789741  1.650307  1.698485
...        ...       ...       ...       ...       ...       ...
1455 -0.071836 -0.542435  0.250402  0.789741  0.311725 -0.060731
1456 -0.071836  2.355701  1.061367  0.789741  0.311725  0.126420
1457  0.651479  0.065656  1.569647  0.789741 -1.026858 -1.033914
1458 -0.795151 -0.218982 -0.832788 -1.026041 -1.026858 -1.090059
1459 -0.795151  0.241615 -0.493934 -1.026041 -1.026858 -0.921624

[1460 rows x 6 columns]

In [358]:
y7=a[["SalePrice"]]
y7

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [359]:
from sklearn.model_selection import train_test_split

In [360]:
x7train,x7test,y7train,y7test=train_test_split(x7,y7,test_size=0.2,shuffle=True,random_state=2)

In [361]:
from sklearn.preprocessing import  PolynomialFeatures

In [362]:
x7train

0         1         2         3         4         5
455   0.651479  0.205388 -0.520585 -1.026041  0.311725  0.257425
863  -0.795151 -0.037848 -0.699531 -1.026041 -1.026858  0.931167
504  -0.071836 -0.796021 -0.368292  0.789741  0.311725 -0.154306
1413  1.374795  1.763136  0.625426  0.789741  0.311725  0.687871
1389 -0.071836 -0.759795 -0.566274 -1.026041  0.311725 -0.154306
...        ...       ...       ...       ...       ...       ...
466   0.651479  0.295955 -0.453957 -1.026041  0.311725  0.248067
299  -0.071836 -0.027498 -0.691916 -1.026041 -1.026858 -0.809333
493  -0.795151  0.275254 -0.469186 -1.026041 -1.026858 -0.771903
527   2.098110  0.810891  2.279717  0.789741  1.650307  1.801418
1192 -0.795151 -0.829660 -0.082741 -1.026041 -1.026858 -1.043272

[1168 rows x 6 columns]

In [363]:
x7test

0         1         2         3         4         5
503   0.651479  1.651868  0.543568  0.789741  0.311725  0.051559
101  -0.071836 -0.480332  0.412214  0.789741  0.311725  0.014129
608   1.374795  2.011548  3.195384  0.789741  0.311725 -0.435032
1089  1.374795  0.218326 -0.511067 -1.026041  0.311725  0.360358
819   0.651479  0.505552 -0.299759  0.789741  0.311725  0.051559
...        ...       ...       ...       ...       ...       ...
816  -0.795151 -0.400115 -0.966045 -1.026041 -1.026858 -0.926303
1273 -0.071836  0.502964 -0.301663 -1.026041 -1.026858 -0.753188
285   0.651479 -1.391174 -0.505356  0.789741  0.311725  0.257425
194  -0.795151 -0.772733 -1.240174 -1.026041 -1.026858 -0.566038
318   0.651479  0.541779  2.152171  0.789741  1.650307  0.856307

[292 rows x 6 columns]

In [364]:
poly=PolynomialFeatures(degree=2)

In [365]:
x7train=poly.fit_transform(x7train)
x7test=poly.fit_transform(x7test)

In [366]:
x7train

array([[ 1.        ,  0.65147924,  0.20538801, ...,  0.09717225,
         0.08024572,  0.06626764],
       [ 1.        , -0.79515147, -0.03784839, ...,  1.05443664,
        -0.95617616,  0.86707235],
       [ 1.        , -0.07183611, -0.79602141, ...,  0.09717225,
        -0.04810108,  0.02381044],
       ...,
       [ 1.        , -0.79515147,  0.27525378, ...,  1.05443664,
         0.79263483,  0.59583473],
       [ 1.        ,  2.09810996,  0.81089137, ...,  2.723513  ,
         2.97289183,  3.24510508],
       [ 1.        , -0.79515147, -0.82966049, ...,  1.05443664,
         1.07129152,  1.08841583]])

In [367]:
x7test

array([[ 1.00000000e+00,  6.51479243e-01,  1.65186828e+00, ...,
         9.71722538e-02,  1.60723204e-02,  2.65836668e-03],
       [ 1.00000000e+00, -7.18361143e-02, -4.80331623e-01, ...,
         9.71722538e-02,  4.40442914e-03,  1.99635136e-04],
       [ 1.00000000e+00,  1.37479460e+00,  2.01154763e+00, ...,
         9.71722538e-02, -1.35610266e-01,  1.89253037e-01],
       ...,
       [ 1.00000000e+00,  6.51479243e-01, -1.39117430e+00, ...,
         9.71722538e-02,  8.02457221e-02,  6.62676398e-02],
       [ 1.00000000e+00, -7.95151472e-01, -7.72732823e-01, ...,
         1.05443664e+00,  5.81240091e-01,  3.20398620e-01],
       [ 1.00000000e+00,  6.51479243e-01,  5.41778766e-01, ...,
         2.72351300e+00,  1.41316931e+00,  7.33261605e-01]])

In [368]:
poly.fit(x7train,y7train)

PolynomialFeatures()

In [369]:
from sklearn.linear_model import LinearRegression

In [370]:
model=LinearRegression()

In [371]:
model.fit(x7train,y7train)

LinearRegression()

In [372]:
model.predict(x7test)

array([[241315.70523411],
       [179627.16059186],
       [322844.1818042 ],
       [214169.12523746],
       [198692.48350137],
       [213226.5162173 ],
       [222124.74495108],
       [178896.47771975],
       [115719.81213293],
       [346608.01301686],
       [194381.51842861],
       [198692.48350137],
       [ 91667.47529619],
       [141571.82838014],
       [ 82255.47041393],
       [246056.02005913],
       [291246.62186584],
       [283741.73463128],
       [235231.30878038],
       [305069.34288047],
       [334425.58637174],
       [157027.60684633],
       [193473.31182205],
       [253372.07991055],
       [482488.3002488 ],
       [234936.78545539],
       [186954.81600393],
       [243733.65251041],
       [215079.78493116],
       [391798.42331764],
       [317127.36900151],
       [163160.89584796],
       [291959.60548679],
       [114502.44645783],
       [191038.95772163],
       [224437.69234296],
       [127568.37238443],
       [320995.4354202 ],
       [3425

In [373]:
mean_absolute_error(y7test,model.predict(x7test))

21435.724866006844

In [374]:
mean_squared_error(y7test,model.predict(x7test))

908122888.5708122

In [375]:
r2_score(y7test,model.predict(x7test))

0.8628682419369283

In [376]:
model.score(x7test,y7test)

0.8628682419369283

In [377]:
b.loc["Polynomial with StandardScaler"]=["StandardScaler","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [378]:
b.loc["Poly_StandardScaler_score"]=[model.score(x7test,y7test),mean_absolute_error(y7test,model.predict(x7test)),mean_squared_error(y7test,model.predict(x7test)),r2_score(y7test,model.predict(x7test))]

In [379]:
b.loc[".============================."]=["=============","=============","=============","=========="]

In [380]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                                    0.606761         38885.804118   
===================                           =======         ============   
MultiVenient                       Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                            0.78866         24994.306499   
=======================                 =============        =============   
Polynomial                           Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                             0.818583         26132.909969   
======================                  =============        =============   
Unuverient with StandardScaler    StandardScale_Score  Mean_Absolute_Error   
StandardScaler_score                         0.515028         40232.132299   
=============================           =============        =============   
Univerient with MinMaxScaler             MinMaxScaler  Mean_Absolute_Error   
MinMaxScaler_score                           0.606761         38885.804118   
============================            =============        =============   
Multivenient with StandardScaler       StandardScaler  Mean_Absolute_Error   
 Multi_StandardScaler_score                  0.818583         26132.909969   
=============================-          =============        =============   
Multivenient with MinMaxScaler           MinMaxScaler  Mean_Absolute_Error   
Multi_MinMaxScaler_score                     0.818583         26132.909969   
============================.-          =============        =============   
Polynomial with StandardScaler         StandardScaler  Mean_Absolute_Error   
Poly_StandardScaler_score                    0.862868         21435.724866   
.============================.          =============        =============   

                                  Mean_Squared_Error    R2_Score  
Univerent                          3115481567.090574    0.606761  
===================                     ============     =======  
MultiVenient                      Mean_Squared_Error    R2_Score  
MultiVenient_score                 1220577200.423954     0.78866  
=======================                =============  ==========  
Polynomial                        Mean_Squared_Error    R2_Score  
Polynomial_score                   1437292992.448363    0.818583  
======================                 =============  ==========  
Unuverient with StandardScaler    Mean_Squared_Error    R2_Score  
StandardScaler_score               3851185498.488252    0.515028  
=============================          =============  ==========  
Univerient with MinMaxScaler      Mean_Squared_Error    R2_Score  
MinMaxScaler_score                 3115481567.090574    0.606761  
============================           =============  ==========  
Multivenient with StandardScaler  Mean_Squared_Error    R2_Score  
 Multi_StandardScaler_score        1437292992.448415    0.818583  
=============================-         =============  ==========  
Multivenient with MinMaxScaler    Mean_Squared_Error    R2_Score  
Multi_MinMaxScaler_score           1437292992.448417    0.818583  
============================.-         =============  ==========  
Polynomial with StandardScaler    Mean_Squared_Error    R2_Score  
Poly_StandardScaler_score           908122888.570812    0.862868  
.============================.         =============  ==========

# MinMaxScaler with Polynomial Regression

In [381]:
from sklearn.preprocessing import MinMaxScaler

In [382]:
MMS=MinMaxScaler()

In [383]:
p8=a[["OverallQual","1stFlrSF","GrLivArea","FullBath","GarageCars","GarageArea"]]
p8

OverallQual  1stFlrSF  GrLivArea  FullBath  GarageCars  GarageArea
0               7       856       1710         2           2         548
1               6      1262       1262         2           2         460
2               7       920       1786         2           2         608
3               7       961       1717         1           3         642
4               8      1145       2198         2           3         836
...           ...       ...        ...       ...         ...         ...
1455            6       953       1647         2           2         460
1456            6      2073       2073         2           2         500
1457            7      1188       2340         2           1         252
1458            5      1078       1078         1           1         240
1459            5      1256       1256         1           1         276

[1460 rows x 6 columns]

In [384]:
p9=MMS.fit_transform(p8)
p9

array([[0.66666667, 0.11977972, 0.25923135, 0.66666667, 0.5       ,
        0.3864598 ],
       [0.55555556, 0.21294172, 0.17483044, 0.66666667, 0.5       ,
        0.32440056],
       [0.66666667, 0.13446535, 0.27354936, 0.66666667, 0.5       ,
        0.42877292],
       ...,
       [0.66666667, 0.19596145, 0.37792012, 0.66666667, 0.25      ,
        0.17771509],
       [0.44444444, 0.17072051, 0.14016579, 0.33333333, 0.25      ,
        0.16925247],
       [0.44444444, 0.21156494, 0.17370008, 0.33333333, 0.25      ,
        0.19464034]])

In [385]:
x8=pd.DataFrame(p9)
x8

0         1         2         3     4         5
0     0.666667  0.119780  0.259231  0.666667  0.50  0.386460
1     0.555556  0.212942  0.174830  0.666667  0.50  0.324401
2     0.666667  0.134465  0.273549  0.666667  0.50  0.428773
3     0.666667  0.143873  0.260550  0.333333  0.75  0.452750
4     0.777778  0.186095  0.351168  0.666667  0.75  0.589563
...        ...       ...       ...       ...   ...       ...
1455  0.555556  0.142038  0.247362  0.666667  0.50  0.324401
1456  0.555556  0.399036  0.327619  0.666667  0.50  0.352609
1457  0.666667  0.195961  0.377920  0.666667  0.25  0.177715
1458  0.444444  0.170721  0.140166  0.333333  0.25  0.169252
1459  0.444444  0.211565  0.173700  0.333333  0.25  0.194640

[1460 rows x 6 columns]

In [386]:
y8=y
y8

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [387]:
from sklearn.model_selection import train_test_split

In [388]:
x8train,x8test,y8train,y8test=train_test_split(x8,y8,test_size=0.2,shuffle=True,random_state=2)

In [389]:
x8train

0         1         2         3     4         5
455   0.666667  0.208352  0.171063  0.333333  0.50  0.372355
863   0.444444  0.186783  0.153353  0.333333  0.25  0.473907
504   0.555556  0.119550  0.186134  0.666667  0.50  0.310296
1413  0.777778  0.346489  0.284476  0.666667  0.50  0.437236
1389  0.555556  0.122763  0.166541  0.333333  0.50  0.310296
...        ...       ...       ...       ...   ...       ...
466   0.666667  0.216384  0.177656  0.333333  0.50  0.370945
299   0.555556  0.187701  0.154107  0.333333  0.25  0.211566
493   0.444444  0.214548  0.176149  0.333333  0.25  0.217207
527   0.888889  0.262047  0.448191  0.666667  0.75  0.605078
1192  0.444444  0.116567  0.214393  0.333333  0.25  0.176305

[1168 rows x 6 columns]

In [390]:
x8test

0         1         2         3     4         5
503   0.666667  0.336622  0.276375  0.666667  0.50  0.341326
101   0.555556  0.147545  0.263376  0.666667  0.50  0.335684
608   0.777778  0.368518  0.538809  0.666667  0.50  0.267983
1089  0.777778  0.209500  0.172005  0.333333  0.50  0.387870
819   0.666667  0.234970  0.192916  0.666667  0.50  0.341326
...        ...       ...       ...       ...   ...       ...
816   0.444444  0.154658  0.126978  0.333333  0.25  0.193935
1273  0.555556  0.234741  0.192728  0.333333  0.25  0.220028
285   0.666667  0.066774  0.172570  0.666667  0.50  0.372355
194   0.444444  0.121615  0.099849  0.333333  0.25  0.248237
318   0.666667  0.238183  0.435569  0.666667  0.75  0.462623

[292 rows x 6 columns]

In [391]:
from sklearn.preprocessing import PolynomialFeatures

In [392]:
poly=PolynomialFeatures(degree=2)

In [393]:
x8train=poly.fit_transform(x8train)
x8test=poly.fit_transform(x8test)

In [394]:
x8train

array([[1.        , 0.66666667, 0.20835246, ..., 0.25      , 0.18617772,
        0.13864857],
       [1.        , 0.44444444, 0.18678293, ..., 0.0625    , 0.11847673,
        0.22458776],
       [1.        , 0.55555556, 0.11955025, ..., 0.25      , 0.1551481 ,
        0.09628373],
       ...,
       [1.        , 0.44444444, 0.21454796, ..., 0.0625    , 0.05430183,
        0.04717903],
       [1.        , 0.88888889, 0.26204681, ..., 0.5625    , 0.45380818,
        0.36611887],
       [1.        , 0.44444444, 0.11656723, ..., 0.0625    , 0.04407616,
        0.03108333]])

In [395]:
x8test

array([[1.        , 0.66666667, 0.3366223 , ..., 0.25      , 0.17066291,
        0.11650331],
       [1.        , 0.55555556, 0.14754475, ..., 0.25      , 0.16784203,
        0.11268379],
       [1.        , 0.77777778, 0.36851767, ..., 0.25      , 0.13399154,
        0.07181493],
       ...,
       [1.        , 0.66666667, 0.06677375, ..., 0.25      , 0.18617772,
        0.13864857],
       [1.        , 0.44444444, 0.12161542, ..., 0.0625    , 0.06205924,
        0.06162159],
       [1.        , 0.66666667, 0.23818265, ..., 0.5625    , 0.34696756,
        0.21402042]])

In [396]:
poly.fit(x8train,y8train)

PolynomialFeatures()

In [397]:
from sklearn.linear_model import LinearRegression

In [398]:
model=LinearRegression()

In [399]:
model.fit(x8train,y8train)

LinearRegression()

In [400]:
model.predict(x8test)

array([[241315.70523411],
       [179627.16059186],
       [322844.1818042 ],
       [214169.12523746],
       [198692.48350137],
       [213226.5162173 ],
       [222124.74495108],
       [178896.47771975],
       [115719.81213293],
       [346608.01301686],
       [194381.51842861],
       [198692.48350137],
       [ 91667.47529619],
       [141571.82838014],
       [ 82255.47041393],
       [246056.02005913],
       [291246.62186584],
       [283741.73463128],
       [235231.30878038],
       [305069.34288047],
       [334425.58637174],
       [157027.60684633],
       [193473.31182205],
       [253372.07991055],
       [482488.3002488 ],
       [234936.78545539],
       [186954.81600393],
       [243733.65251041],
       [215079.78493116],
       [391798.42331764],
       [317127.36900151],
       [163160.89584796],
       [291959.60548679],
       [114502.44645783],
       [191038.95772163],
       [224437.69234296],
       [127568.37238443],
       [320995.4354202 ],
       [3425

In [401]:
mean_absolute_error(y8test,model.predict(x8test))

21435.724866006836

In [402]:
mean_squared_error(y8test,model.predict(x8test))

908122888.5708117

In [403]:
r2_score(y8test,model.predict(x8test))

0.8628682419369285

In [404]:
model.score(x8test,y8test)

0.8628682419369285

In [405]:
b.loc["Polynomial with MinMaxScaler"]=["MinMaxScaler","Mean_Absolute_Error","Mean_Squared_Error","R2_Score"]

In [406]:
b.loc["polynomial_MinMaxScaler_score"]=[model.score(x8test,y8test),mean_absolute_error(y8test,model.predict(x8test)),mean_squared_error(y8test,model.predict(x8test)),r2_score(y8test,model.predict(x8test))]

In [407]:
b.loc[".____________________________."]=["_________________","___________________","__________________","________________"]

In [408]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                                    0.606761         38885.804118   
===================                           =======         ============   
MultiVenient                       Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                            0.78866         24994.306499   
=======================                 =============        =============   
Polynomial                           Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                             0.818583         26132.909969   
======================                  =============        =============   
Unuverient with StandardScaler    StandardScale_Score  Mean_Absolute_Error   
StandardScaler_score                         0.515028         40232.132299   
=============================           =============        =============   
Univerient with MinMaxScaler             MinMaxScaler  Mean_Absolute_Error   
MinMaxScaler_score                           0.606761         38885.804118   
============================            =============        =============   
Multivenient with StandardScaler       StandardScaler  Mean_Absolute_Error   
 Multi_StandardScaler_score                  0.818583         26132.909969   
=============================-          =============        =============   
Multivenient with MinMaxScaler           MinMaxScaler  Mean_Absolute_Error   
Multi_MinMaxScaler_score                     0.818583         26132.909969   
============================.-          =============        =============   
Polynomial with StandardScaler         StandardScaler  Mean_Absolute_Error   
Poly_StandardScaler_score                    0.862868         21435.724866   
.============================.          =============        =============   
Polynomial with MinMaxScaler             MinMaxScaler  Mean_Absolute_Error   
polynomial_MinMaxScaler_score                0.862868         21435.724866   
.____________________________.      _________________  ___________________   

                                  Mean_Squared_Error          R2_Score  
Univerent                          3115481567.090574          0.606761  
===================                     ============           =======  
MultiVenient                      Mean_Squared_Error          R2_Score  
MultiVenient_score                 1220577200.423954           0.78866  
=======================                =============        ==========  
Polynomial                        Mean_Squared_Error          R2_Score  
Polynomial_score                   1437292992.448363          0.818583  
======================                 =============        ==========  
Unuverient with StandardScaler    Mean_Squared_Error          R2_Score  
StandardScaler_score               3851185498.488252          0.515028  
=============================          =============        ==========  
Univerient with MinMaxScaler      Mean_Squared_Error          R2_Score  
MinMaxScaler_score                 3115481567.090574          0.606761  
============================           =============        ==========  
Multivenient with StandardScaler  Mean_Squared_Error          R2_Score  
 Multi_StandardScaler_score        1437292992.448415          0.818583  
=============================-         =============        ==========  
Multivenient with MinMaxScaler    Mean_Squared_Error          R2_Score  
Multi_MinMaxScaler_score           1437292992.448417          0.818583  
============================.-         =============        ==========  
Polynomial with StandardScaler    Mean_Squared_Error          R2_Score  
Poly_StandardScaler_score           908122888.570812          0.862868  
.============================.         =============        ==========  
Polynomial with MinMaxScaler      Mean_Squared_Error          R2_Score  
polynomial_MinMaxScaler_score       908122888.570812          0.862868  
.____________________________.  

In [409]:
data=pd.read_csv("Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [410]:
xx=data[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
xx

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [411]:
x.isnull().sum()

GrLivArea    0
dtype: int64

In [412]:
g=data[["Species"]]
g

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [458]:
g.value_counts()

Species        
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

#### Now Replace

In [459]:
yy=g.replace(["Iris-setosa","Iris-versicolor","Iris-virginica"],[0,1,2])
yy

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [460]:
xx.shape

(150, 4)

In [461]:
yy.shape

(150, 1)

In [462]:
yy

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

# KNeighborsClassifier Algorithm

In [463]:
from sklearn.model_selection import train_test_split

In [464]:
xxtrain,xxtest,yytrain,yytest=train_test_split(xx,yy,test_size=0.1,shuffle=True,random_state=2)

In [470]:
from sklearn.neighbors import KNeighborsClassifier

#### All Parameters Use in KNeighborsClassifier

In [466]:
KNN=KNeighborsClassifier(n_neighbors=5,weights='uniform',algorithm='auto',leaf_size=30,p=2,metric='minkowski',metric_params=None,n_jobs=None)

In [467]:
KNN.fit(xxtrain,yytrain)

C:\Users\Umar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [468]:
KNN.predict(xxtest)

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor'], dtype=object)

In [457]:
KNN.score(xxtest,yytest)

1.0

# Support Vector Machine

In [425]:
from sklearn.svm import SVC

#### All parementer use in Support Vector Machine

In [426]:
support= SVC( kernel='linear',degree=3,gamma='scale',coef0=0.0,shrinking=True,probability=False,tol=0.001,cache_size=200,class_weight=None,verbose=False,max_iter=-1,decision_function_shape='ovr',break_ties=False,random_state=None)

In [427]:
support.fit(xxtrain,yytrain)

C:\Users\Umar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='linear')

In [428]:
support.predict(xxtest)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1], dtype=int64)

In [429]:
support.score(xxtest,yytest)

1.0

# Decision_Tree

In [430]:
from sklearn.tree import DecisionTreeClassifier

In [431]:
xxtrain,xxtest,yytrain,yytest=train_test_split(xx,yy,test_size=0.1,shuffle=False,random_state=2)

#### All Paremeter use in DecisionTreeClassifier

In [432]:
DTC=DecisionTreeClassifier(criterion='gini',splitter='best',max_depth=None,min_samples_split=2,min_samples_leaf=1,min_weight_fraction_leaf=0.0,max_features=None,random_state=None,max_leaf_nodes=None,min_impurity_decrease=0.0,min_impurity_split=None,class_weight=None,ccp_alpha=0.0)

In [433]:
DTC.fit(xxtrain,yytrain)

DecisionTreeClassifier()

In [434]:
DTC.predict(xxtest)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [435]:
DTC.score(xxtest,yytest)

1.0

# RandomForestClassifier Algorithm

In [436]:
from sklearn.ensemble import RandomForestClassifier

In [437]:
xxtrain,xxtest,yytrain,yytest=train_test_split(xx,yy,test_size=0.1,shuffle=False,random_state=2)

#### All Paremeter use in RandomForestClassifier

In [438]:
random=RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=None,min_samples_split=2,min_samples_leaf=1,min_weight_fraction_leaf=0.0,max_features='auto',max_leaf_nodes=None,min_impurity_decrease=0.0,min_impurity_split=None,bootstrap=True,oob_score=False,n_jobs=None,random_state=None,verbose=0,warm_start=False,class_weight=None,ccp_alpha=0.0,max_samples=None)

In [439]:
random.fit(xxtrain,yytrain)

<ipython-input-439-6c82f50afaef>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random.fit(xxtrain,yytrain)


RandomForestClassifier()

In [440]:
random.predict(xxtest)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [441]:
random.score(xxtest,yytest)

1.0

# Logistic Regression

In [442]:
from sklearn.linear_model import LogisticRegression

In [443]:
xxtrain,xxtest,yytrain,yytest=train_test_split(xx,yy,test_size=0.1,shuffle=True,random_state=2)

#### All parameter use in LogisticRegression

In [444]:
log=LogisticRegression(penalty='l2',dual=False,tol=0.0001,C=1.0,fit_intercept=True,intercept_scaling=1,class_weight=None,random_state=None,solver='lbfgs',max_iter=100,multi_class='auto',verbose=0,warm_start=False,n_jobs=None,l1_ratio=None)

In [445]:
log.fit(xxtrain,yytrain)

C:\Users\Umar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [446]:
log.predict(xxtest)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1], dtype=int64)

In [447]:
log.predict_proba(xxtest)

array([[9.83734070e-01, 1.62658865e-02, 4.29949588e-08],
       [9.70338029e-01, 2.96618905e-02, 8.08635950e-08],
       [2.69653277e-04, 1.55152934e-01, 8.44577413e-01],
       [9.67810041e-01, 3.21899153e-02, 4.37122382e-08],
       [9.42310454e-01, 5.76891455e-02, 4.00809715e-07],
       [2.27529630e-05, 1.61714415e-01, 8.38262832e-01],
       [9.40426688e-01, 5.95731450e-02, 1.66524789e-07],
       [7.46270962e-06, 6.53292552e-02, 9.34663282e-01],
       [1.41956285e-05, 4.11464573e-02, 9.58839347e-01],
       [9.67389833e-01, 3.26100868e-02, 8.03125766e-08],
       [9.74144554e-01, 2.58554062e-02, 3.97952046e-08],
       [9.86033773e-01, 1.39662028e-02, 2.45087858e-08],
       [9.80673942e-01, 1.93260408e-02, 1.70692671e-08],
       [9.65584721e-01, 3.44151268e-02, 1.52125563e-07],
       [1.05222360e-02, 7.68273630e-01, 2.21204134e-01]])

In [448]:
log.score(xxtest,yytest)

1.0

In [449]:
from sklearn.metrics import accuracy_score

In [450]:
accuracy_score(yytest,log.predict(xxtest))

1.0

In [451]:
v=[KNN.score(xxtest,yytest)]
p=pd.DataFrame(v,columns=["KNeighborsClassifier"],index=["score"])
p["Support Vector Machine"]=[support.score(xxtest,yytest)]
p[" Decision_Tree"]=[DTC.score(xxtest,yytest)]
p["RandomForest"]=[random.score(xxtest,yytest)]
p["LogisticRegression"]=[log.score(xxtest,yytest)]
p["LogisticRegression_Accuracy Score"]=[accuracy_score(yytest,log.predict(xxtest))]


# Discrete Data Score

In [452]:
p.T

score
KNeighborsClassifier                 1.0
Support Vector Machine               1.0
 Decision_Tree                       1.0
RandomForest                         1.0
LogisticRegression                   1.0
LogisticRegression_Accuracy Score    1.0

# Continous Data Score

In [453]:
b

Univerient_Score  Mean_Absolute_Error  \
Univerent                                    0.606761         38885.804118   
===================                           =======         ============   
MultiVenient                       Multiverient_Score  Mean_Absolute_Error   
MultiVenient_score                            0.78866         24994.306499   
=======================                 =============        =============   
Polynomial                           Polynomial_Score  Mean_Absolute_Error   
Polynomial_score                             0.818583         26132.909969   
======================                  =============        =============   
Unuverient with StandardScaler    StandardScale_Score  Mean_Absolute_Error   
StandardScaler_score                         0.515028         40232.132299   
=============================           =============        =============   
Univerient with MinMaxScaler             MinMaxScaler  Mean_Absolute_Error   
MinMaxScaler_score                           0.606761         38885.804118   
============================            =============        =============   
Multivenient with StandardScaler       StandardScaler  Mean_Absolute_Error   
 Multi_StandardScaler_score                  0.818583         26132.909969   
=============================-          =============        =============   
Multivenient with MinMaxScaler           MinMaxScaler  Mean_Absolute_Error   
Multi_MinMaxScaler_score                     0.818583         26132.909969   
============================.-          =============        =============   
Polynomial with StandardScaler         StandardScaler  Mean_Absolute_Error   
Poly_StandardScaler_score                    0.862868         21435.724866   
.============================.          =============        =============   
Polynomial with MinMaxScaler             MinMaxScaler  Mean_Absolute_Error   
polynomial_MinMaxScaler_score                0.862868         21435.724866   
.____________________________.      _________________  ___________________   

                                  Mean_Squared_Error          R2_Score  
Univerent                          3115481567.090574          0.606761  
===================                     ============           =======  
MultiVenient                      Mean_Squared_Error          R2_Score  
MultiVenient_score                 1220577200.423954           0.78866  
=======================                =============        ==========  
Polynomial                        Mean_Squared_Error          R2_Score  
Polynomial_score                   1437292992.448363          0.818583  
======================                 =============        ==========  
Unuverient with StandardScaler    Mean_Squared_Error          R2_Score  
StandardScaler_score               3851185498.488252          0.515028  
=============================          =============        ==========  
Univerient with MinMaxScaler      Mean_Squared_Error          R2_Score  
MinMaxScaler_score                 3115481567.090574          0.606761  
============================           =============        ==========  
Multivenient with StandardScaler  Mean_Squared_Error          R2_Score  
 Multi_StandardScaler_score        1437292992.448415          0.818583  
=============================-         =============        ==========  
Multivenient with MinMaxScaler    Mean_Squared_Error          R2_Score  
Multi_MinMaxScaler_score           1437292992.448417          0.818583  
============================.-         =============        ==========  
Polynomial with StandardScaler    Mean_Squared_Error          R2_Score  
Poly_StandardScaler_score           908122888.570812          0.862868  
.============================.         =============        ==========  
Polynomial with MinMaxScaler      Mean_Squared_Error          R2_Score  
polynomial_MinMaxScaler_score       908122888.570812          0.862868  
.____________________________.  